---
title: "pib - Replication script"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pib - Replication script}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

This document shows how to replicate the analyses reported in
Schuessler, J., Glynn, A. N., & Rueda, M.R. (2025). "Post-Instrument
Bias".
```{r setup, eval=FALSE}
library(pib)
library(estimatr)
library(broom)
```

### Setup

```{r, eval = FALSE}
data("hong_data")

y <- "E18ConsSh"
d <- "total_Lamount_1974_1978_perelect"
m <- "demo_female_share_1966"
z <- c("te_median1", "ts_median1")
x <- c("area_1970",  "eup", "demo_age_15plus_1966",
       "demo_illiterate_1966", "demo_pop_ch_1970_1966",
       "E17ConsSh")
fe <- "CTY_cd"

rhs_with_m_and_z <- c(x, m, z)
rhs_with_m       <- c(x, m)
rhs_no_m         <- x

fe_formula <- reformulate(fe)             
```

### Diagnostic test

```{r, eval=FALSE}
diag_form <- reformulate(rhs_with_m_and_z, response = d)


confint(lm_robust(formula = diag_form, data = hong_data,
          clusters = CTY_cd, fixed_effects = ~ CTY_cd), 
        level = 0.9)["demo_female_share_1966",]


```
### IV Treatment Effect Estimation with and without M

```{r, eval=FALSE}
iv_with_m_formula <- as.formula(paste(
  y, "~", paste(c(d, rhs_with_m), collapse = " + "), "|",
  paste(c(rhs_with_m, z), collapse = " + ")
))

tidy(iv_robust(formula = iv_with_m_formula, data = hong_data,
          clusters = CTY_cd, fixed_effects = ~ CTY_cd))[1,]
```


```{r, eval=FALSE}
iv_no_m_formula <- as.formula(paste(
  y, "~", paste(c(d, rhs_no_m), collapse = " + "), "|",
  paste(c(rhs_no_m, z), collapse = " + ")
))

tidy(iv_robust(formula = iv_no_m_formula, data = hong_data,
          clusters = CTY_cd, fixed_effects = ~ CTY_cd))[1,]
```

### M as outcome in first stage regression

```{r, eval = FALSE}
first_stage_m_form <- reformulate(c(rhs_no_m, z), response = m)


tidy(lm_robust(formula = first_stage_m_form, data = hong_data,
          clusters = CTY_cd, fixed_effects = ~ CTY_cd))[7:8,]
```

### IV with M as outcome

```{r, eval = FALSE}
iv_m_outcome_form <- as.formula(paste(
  m, "~", paste(c(d, rhs_no_m), collapse = " + "), "|",
  paste(c(rhs_no_m, z), collapse = " + ")
))

tidy(iv_robust(formula = iv_m_outcome_form, data = hong_data,
          clusters = CTY_cd, fixed_effects = ~ CTY_cd))[1,]
```


### Sensitivity analysis

```{r, eval=FALSE}
out <- estimate_sensitivity(hong_data, outcome = y, 
                            treat = d, 
                            inst = z, 
                            post.inst = m, 
                            x = x,
                            fe = fe, seed = 2893, R = 1000,
                            parallel = "multicore")

gamma <- c(-1, 1)
sigma <- c(0, 0.2)

bounds <- post_instrument_bounds(gamma = gamma, sigma = sigma,
                                 estimates = out)


```

```{r, eval = FALSE}
plot_pib_bounds(bounds)


```
```{r, eval = FALSE}
# high variance Beta distribution with causal effects varying from 0 to 0.5
beta_sd(0.5, 0.5, -0.1, 0.4)
# low variance
beta_sd(4, 4, -0.1, 0.4)

compute_single_bounds(gamma = 0.15, sigma = 0.08, bounds = bounds)
```

